export const styles = {
  fitContent: 'width: fit-content; height: fit-content;',
  borderRadius: 'border-radius: var(--border-radius);',
  border: 'border: 1px solid var(--gray-border);',
  borderLeft: 'border-left: 1px solid var(--gray-border);',
  borderRight: 'border-right: 1px solid var(--gray-border);',
  borderBottom: 'border-bottom: 1px solid var(--gray-border);',
  borderTop: 'border-top: 1px solid var(--gray-border);',
  textLabel: `font-size: 12px;`,
  textCommon: `font-size: 13px;`,
  textHead: `font-size: 12px;font-weight: 600;`,
  bgPrimary: `background-color: var(--color-bg);`,
  bgHoverPrimary: `&:hover {background-color: var(--color-bg);}`,
  bgHoverGray: `&:hover {background-color: var(--gray-bg);}`,
}
