npx swagger-typescript-api generate \
-p http://127.0.0.1:3001/api-docs-json \
-o src/global/api \
-n api.ts \
--silent \
--unwrap-response-data \
--axios \
--api-class-name API \
--clean-output \
--extract-request-body \
--extract-response-body \
--default-as-success
